apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: web
  # StrategyType: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: flask-app
        image: 244282014725.dkr.ecr.us-east-1.amazonaws.com/sprints-ecr:v1
        # image: flask-app:v1
        # never pull the image policy
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        # DB_HOST: db
        # DB_PORT: 3306
        # DB_NAME: BucketList
        # DB_USER: root
        # DB_PASSWORD: root
        - name: DB_HOST
          value: mysql-headless
          # valueFrom: 
          #   secretKeyRef: 
          #     key: DB_HOST
          #     name: db-secret
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom: 
            secretKeyRef: 
              key: DATABASE
              name: db-secret
          # value: BucketList
        - name: DB_USER
          valueFrom: 
            secretKeyRef: 
              key: DB_USER
              name: db-secret
          # value: root
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef: 
              key: ROOT_PASSWORD
              name: db-secret
          # value: root
        ports:
        - containerPort: 5000
      # volumes:
      # - name: db-init
      #   configMap:
      #     name: initdb-config