apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: mysql-db
spec:
  storageClassName: manual
  
  capacity:
    storage: 2Gi
    # storage: 50Mi
  # persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql

# ---------------------------

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-initdb-pv-volume
#   labels:
#     type: local
#     app: mysql
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Mi
#   accessModes:
#     - ReadOnlyMany
#   hostPath:
#     path: "/home/lenovo/Downloads/task/test/"