apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      # storage: 50Mi

# ----------------------

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-initdb-pv-claim
#   labels:
#     app: mysql
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 1Mi