version: '3.8'
services:
  db:
    image: mysql:v1
    build: ./MySQL-and-Python/MySQL_Queries/Dockerfile
    container_name: mysql_DB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BucketList
    restart: always
    volumes:
      - ./MySQL-and-Python/MySQL_Queries:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: Flask-Web
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: BucketList
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "5000:5000"
    restart: on-failure
    command: python app.py
