version: '3.9'
services:
  db:
    image: mysql:v1
    container_name: docker_file-db-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BucketList
      # MYSQL_ROOT_HOST: '%'
    volumes:
      - ./MySQL-and-Python/MySQL_Queries:/docker-entrypoint-initdb.d
    # command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"

  web:
    networks:
      - default
    build: .
    container_name: docker_file-web-1
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: BucketList
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "5002:5002"
    restart: on-failure
    command: python app.py

networks:
  default:
    driver: bridge
